algoritmo "matriz no teclado - Aula 15"
var
   m : vetor[1..3 , 1..2] de inteiro
   L,C: inteiro
inicio
      para L <- 1 ate 3 faca
           para C <- 1 ate 2 faca
                Escreva("Digite um valor da posição [",l , "," , C, "]: ")
                leia(m[L,C])
           FimPara
      FimPara
      
      Para   L <- 1 ate 3 faca
             Para C <- 1 ate 2 faca
                  Escreva(m[l,c]:5)

             FimPara
             EscrevaL()
      FimPara

fimalgoritmo