algoritmo "Pratica 2 - Procedimento - Aula 12"
var
X , Y : inteiro

Procedimento Soma (var A,B: inteiro)
inicio
      A <- A +1
      B <- B + 1
      EscrevaL("Valor de A = ", A)
      Escreval("Valor de B = ", B)
      Escreval("Soma A + B = ", A+B)
FimProcedimento
inicio
      X <- 4
      Y <- 8
      Soma (X , Y)
      Escreval("Valor de X = ", X)
      Escreval("Valor de Y = ", Y)


fimalgoritmo